export type Lang = 'en' | 'ar'

export const t: Record<Lang, Record<string, string>> = {
  en: {
    'dashboard': 'Dashboard', 'fileAnalysis': 'File Analysis', 'scanLogs': 'Scan Logs',
    'alerts': 'Alerts', 'settings': 'Settings', 'systemActive': 'System Active',
    'totalScans': 'Total Scans', 'ransomwareDetected': 'Ransomware Detected',
    'safeFiles': 'Safe Files', 'avgConfidence': 'Avg Confidence',
    'recentScans': 'Recent Scans', 'detectionRate': 'Detection Rate',
    'noScans': 'No scans yet', 'startScanning': 'Start by uploading a file in File Analysis',
    'filesScanned': 'Files Scanned', 'threatsFound': 'Threats Found', 'lastScan': 'Last Scan',
    'scanResults': 'Scan Results', 'threatRate': 'Threat Rate', 'protectionStatus': 'Protection Status',
    'systemProtected': 'System Protected', 'allFeaturesActive': 'All features active',
    'realtimeProtectionFeat': 'Real-time Protection', 'autoQuarantineFeat': 'Auto Quarantine',
    'scheduledScans': 'Scheduled Scans', 'scanActivity': 'Scan Activity',
    'recentScanResults': 'Recent Scan Results', 'safe': 'Safe', 'threat': 'Threat',
    'monitorDesc': 'Real-time Threat Intelligence & Analytics',
    'lastAction': 'Last Action', 'realtimeShield': 'Real-Time Shield',
    'topRecentThreats': 'Critical Threats', 'nextScheduledScan': 'Next Audit',
    'activeStatus': 'Active', 'total': 'Total',
    'noRecentThreats': 'No threats detected', 'justNow': 'Just now',


    'fileAnalysisTitle': 'File Analysis', 'fileAnalysisDesc': 'Detect ransomware in Windows executable files',
    'dropExe': 'Drop .exe file here', 'exeOnly': 'Windows executable (.exe) files only',
    'browseFile': 'Browse .exe File', 'analyzeBtn': 'Analyze EXE File',
    'scanning': 'Analyzing PE structure & ransomware indicators...',
    'ransomwareDetectedMsg': '🚨 RANSOMWARE DETECTED', 'safeMsg': '✅ FILE IS SAFE',
    'confidence': 'confidence', 'scanAgain': 'Scan Again', 'riskScore': 'Risk Score',
    'highRisk': 'High Risk', 'mediumRisk': 'Medium Risk', 'lowRisk': 'Low Risk',
    'detectionReasons': 'Detection Reasons', 'classification': 'Classification',
    'exeProperties': 'EXE Properties', 'fileType': 'File Type', 'entropy': 'Entropy',
    'signature': 'Signature', 'savedTo': 'Saved to', 'modelMetrics': 'Model Metrics',
    'analysisDetails': 'Analysis Details', 'layerBreakdown': 'Layer Breakdown',
    'sectionEntropy': 'Section Entropy', 'yaraRules': 'YARA Rules', 'apiChains': 'API Chain Detection',
    'sigLayer': 'Signature Scan', 'entropyLayer': 'Entropy Analysis',
    'peLayer': 'PE Structure', 'behaviorLayer': 'Behavior & YARA',
    'layerScore': 'Score', 'layerStatus': 'Status',
    'ruleMatched': 'Matched', 'ruleNotMatched': 'Not Matched',
    'chainDetected': 'Detected', 'chainNotDetected': 'Not Detected',
    'normalEntropy': 'Normal', 'elevatedEntropy': 'Elevated', 'packedSection': 'Packed / Encrypted',
    'sectionName': 'Section', 'sectionSize': 'Size', 'sectionEntropyVal': 'Entropy',
    'ruleName': 'Rule', 'ruleDesc': 'Description', 'chainName': 'Chain', 'chainDesc': 'Description',
    'foundApis': 'Found APIs', 'showDetails': 'Show Analysis Details', 'hideDetails': 'Hide Details',
    'scanLogsTitle': 'Scan Logs', 'scanLogsDesc': 'All scan records from database',
    'noLogs': 'No scan records yet', 'filename': 'Filename', 'time': 'Time',
    'result': 'Result', 'rows': 'Rows', 'accuracy': 'Accuracy',
    'alertsTitle': 'Alerts', 'alertsDesc': 'Security alerts from database',
    'critical': 'Critical', 'warning': 'Warning', 'all': 'All',
    'noAlerts': 'No Alerts', 'noAlertsDesc': 'No ransomware detected in your scans',
    'clearAllAlerts': 'Clear All Alerts', 'clearAllAlertsDesc': 'Remove all ransomware alerts from the database',
    'clearAllAlertsConfirm': 'Delete all alerts? This cannot be undone.',
    'clearingAlerts': 'Clearing...',
    'settingsTitle': 'Settings', 'settingsDesc': 'Customize protection and security settings',
    'language': 'Language', 'interfaceLang': 'Interface Language', 'chooseLang': 'Choose your preferred language',
    'protectionSettings': 'Protection Settings', 'realtimeProtection': 'Real-time Protection',
    'realtimeDesc': 'Scan files automatically when accessed', 'autoQuarantine': 'Auto Quarantine',
    'autoQuarantineDesc': 'Move suspicious files to quarantine', 'scanOnStartup': 'Scan on Startup',
    'scanOnStartupDesc': 'Run quick scan when system starts', 'notifications': 'Notifications',
    'notificationsDesc': 'Show alerts when threats are detected', 'updateBackup': 'Update & Backup',
    'autoUpdate': 'Auto Update', 'autoUpdateDesc': 'Automatically update threat database',
    'scheduledScan': 'Scheduled Scan', 'scheduledScanDesc': 'Run full scan daily at 2:00 AM',
    'cloudBackup': 'Cloud Backup', 'cloudBackupDesc': 'Backup important files to cloud',
    'sensitivity': 'Sensitivity Level', 'sensitivityDesc': 'Higher = more alerts, lower = fewer false positives',
    'low': 'Low', 'medium': 'Medium', 'high': 'High', 'dangerZone': 'Danger Zone',
    'clearAll': 'Clear All Scan Data', 'clearDesc': 'Deletes all records from SQLite database permanently',
    'clearDB': 'Clear DB', 'save': 'Save', 'saved': 'Saved!', 'reset': 'Reset',
    'login': 'Sign In', 'register': 'Create Account', 'email': 'Email Address',
    'password': 'Password', 'confirmPassword': 'Confirm Password', 'username': 'Username',
    'loginBtn': 'Sign In', 'registerBtn': 'Create Account',
    'noAccount': "Don't have an account?", 'hasAccount': 'Already have an account?',
    'signUpLink': 'Sign up', 'signInLink': 'Sign in',
    'emailPlaceholder': 'Enter your email', 'passwordPlaceholder': 'Enter your password',
    'Forgot Password': 'Forgot Password',
    'forgotPassword': 'Forgot Password',
    'Send Code': 'Send Code',
    'Reset Code': 'Reset Code',
    'New Password': 'New Password',
    'Reset Password': 'Reset Password',
    'confirmPasswordPlaceholder': 'Re-enter your password', 'usernamePlaceholder': 'Choose a username',
    'verifyEmail': 'Verify Your Email', 'verifyDesc': 'We sent a 6-digit code to',
    'verifyCode': 'Verification Code', 'verifyBtn': 'Verify Email',
    'resendCode': 'Resend Code', 'resendIn': 'Resend in', 'seconds': 's',
    'verifyPlaceholder': 'Enter 6-digit code', 'loginSuccess': 'Welcome back!',
    'logoutBtn': 'Logout', 'loggedInAs': 'Logged in as',
    'passwordMismatch': 'Passwords do not match', 'emailInvalid': 'Please enter a valid email',
    'usernameTooShort': 'Username must be at least 3 characters',
    'passwordTooShort': 'Password must be at least 6 characters',
    'accountCreated': 'Account created! Please verify your email.',
    'invalidCode': 'Invalid verification code', 'codeExpired': 'Code expired, please resend',
    'loginError': 'Invalid email or password', 'protectedBy': 'Protected by SARMZ RansomGuard',
    'downloadReport': 'Download PDF Report', 'generatingReport': 'Generating Report...',
    'reportTitle': 'Security Analysis Report', 'reportGenerated': 'Report Generated',
    'reportSubtitle': 'SARMZ RansomGuard - Comprehensive Analysis',
    'reportSummary': 'Executive Summary', 'reportScans': 'Scan History',
    'reportMetrics': 'Model Performance Metrics', 'reportProtection': 'Protection Status',
    'reportFooter': 'Generated by SARMZ RansomGuard - Ransomware Detection System',
    'totalFiles': 'Total Files Scanned', 'threatsBlocked': 'Threats Blocked',
    'safeFilesCount': 'Safe Files', 'avgConfidenceScore': 'Avg. Confidence Score',
    'trainingTitle': 'Model Training',
    'profileSettings': 'Profile Settings',
    'changeUsername': 'Change Username',
    'newUsername': 'New Username',
    'changePassword': 'Change Password',
    'newPassword': 'New Password',
    'updateProfileBtn': 'Update Profile',
    'profileUpdated': 'Profile updated successfully!',
    'aboutTitle': 'About', 'aboutDesc': 'Learn more about SARMZ RansomGuard',
    'aboutWelcome': 'About SARMZ RansomGuard',
    'aboutWelcomeDesc': 'Welcome to SARMZ RansomGuard, an advanced and intelligent platform dedicated to proactive cybersecurity. Our mission is to safeguard your digital environment by detecting and neutralizing ransomware threats before they can cause harm or compromise your valuable data.',
    'aboutApproach': 'Our Approach',
    'aboutApproachDesc': 'Powered by state-of-the-art Artificial Intelligence and Machine Learning algorithms, SARMZ RansomGuard meticulously analyzes Windows executable files (.exe). By examining complex patterns such as file entropy, PE structure, and behavioral YARA rules, our system distinguishes between benign software and malicious ransomware with exceptional accuracy.',
    'aboutWhy': 'Why SARMZ RansomGuard?',
    'aboutWhyDesc': 'As ransomware attacks become increasingly sophisticated, traditional security measures are no longer sufficient. SARMZ RansomGuard bridges this gap by offering a predictive, intelligent defense mechanism. Our seamless user interface provides real-time insights, comprehensive scan logs, and detailed security reports, empowering users with complete control over their system\'s safety.',
    'aboutVision': 'Our Vision',
    'aboutVisionDesc': 'SARMZ RansomGuard represents our commitment to creating practical, modern, and effective technological solutions. We believe that digital security is a fundamental right, and we strive to deliver a tool that combines the power of AI with user-friendly design to combat today\'s most aggressive digital threats.',
    'urlScanner': 'URL Scanner', 'urlScannerDesc': 'Analyze URLs for Phishing and Malware Threats',
    'scanUrlBtn': 'Scan URL', 'enterUrlPlaceholder': 'Enter URL to scan (e.g. https://example.com)',

  },
  ar: {
    'dashboard': 'لوحة التحكم', 'fileAnalysis': 'تحليل الملفات', 'scanLogs': 'سجل الفحص',
    'alerts': 'التنبيهات', 'settings': 'الإعدادات', 'systemActive': 'النظام نشط',
    'urlScanner': 'فحص الروابط', 'urlScannerDesc': 'تحليل الروابط للبحث عن التصيد والبرمجيات الخبيثة',
    'scanUrlBtn': 'فحص الرابط', 'enterUrlPlaceholder': 'أدخل الرابط (مثال: https://example.com)',
    'totalScans': 'إجمالي الفحوصات', 'ransomwareDetected': 'فدية مكتشفة',
    'safeFiles': 'ملفات آمنة', 'avgConfidence': 'متوسط الثقة',
    'recentScans': 'آخر الفحوصات', 'detectionRate': 'معدل الكشف',
    'noScans': 'لا توجد فحوصات', 'startScanning': 'ابدأ برفع ملف في تحليل الملفات',
    'filesScanned': 'الملفات المفحوصة', 'threatsFound': 'التهديدات المكتشفة', 'lastScan': 'آخر فحص',
    'scanResults': 'نتائج الفحص', 'threatRate': 'معدل التهديد', 'protectionStatus': 'حالة الحماية',
    'systemProtected': 'النظام محمي', 'allFeaturesActive': 'جميع الميزات نشطة',
    'realtimeProtectionFeat': 'الحماية الفورية', 'autoQuarantineFeat': 'الحجر التلقائي',
    'scheduledScans': 'الفحص المجدول', 'scanActivity': 'نشاط الفحص',
    'recentScanResults': 'آخر نتائج الفحص', 'safe': 'آمن', 'threat': 'تهديد',
    'monitorDesc': 'مراقبة حالة حماية نظامك',
    'fileAnalysisTitle': 'تحليل الملفات', 'fileAnalysisDesc': 'كشف برامج الفدية في ملفات Windows التنفيذية',
    'dropExe': 'أسقط ملف .exe هنا', 'exeOnly': 'ملفات .exe فقط',
    'browseFile': 'تصفح ملف .exe', 'analyzeBtn': 'تحليل الملف',
    'scanning': 'جارٍ تحليل الملف...',
    'ransomwareDetectedMsg': '🚨 تم اكتشاف برنامج فدية', 'safeMsg': '✅ الملف آمن',
    'confidence': 'الثقة', 'scanAgain': 'فحص مجدداً', 'riskScore': 'درجة الخطر',
    'highRisk': 'خطر عالي', 'mediumRisk': 'خطر متوسط', 'lowRisk': 'خطر منخفض',
    'detectionReasons': 'أسباب الكشف', 'classification': 'التصنيف',
    'exeProperties': 'خصائص الملف', 'fileType': 'نوع الملف', 'entropy': 'الإنتروبيا',
    'signature': 'التوقيع', 'savedTo': 'محفوظ في', 'modelMetrics': 'مقاييس النموذج',
    'analysisDetails': 'تفاصيل التحليل', 'layerBreakdown': 'توزيع الطبقات',
    'sectionEntropy': 'إنتروبيا الأقسام', 'yaraRules': 'قواعد YARA', 'apiChains': 'كشف سلاسل API',
    'sigLayer': 'فحص التوقيعات', 'entropyLayer': 'تحليل الإنتروبيا',
    'peLayer': 'هيكل PE', 'behaviorLayer': 'السلوك و YARA',
    'layerScore': 'الدرجة', 'layerStatus': 'الحالة',
    'ruleMatched': 'متطابق', 'ruleNotMatched': 'غير متطابق',
    'chainDetected': 'مكتشف', 'chainNotDetected': 'غير مكتشف',
    'normalEntropy': 'طبيعي', 'elevatedEntropy': 'مرتفع', 'packedSection': 'مضغوط / مشفر',
    'sectionName': 'القسم', 'sectionSize': 'الحجم', 'sectionEntropyVal': 'الإنتروبيا',
    'ruleName': 'القاعدة', 'ruleDesc': 'الوصف', 'chainName': 'السلسلة', 'chainDesc': 'الوصف',
    'foundApis': 'الـ APIs المكتشفة', 'showDetails': 'عرض تفاصيل التحليل', 'hideDetails': 'إخفاء التفاصيل',
    'scanLogsTitle': 'سجل الفحص', 'scanLogsDesc': 'جميع سجلات الفحص من قاعدة البيانات',
    'noLogs': 'لا توجد سجلات بعد', 'filename': 'اسم الملف', 'time': 'الوقت',
    'result': 'النتيجة', 'rows': 'الصفوف', 'accuracy': 'الدقة',
    'alertsTitle': 'التنبيهات', 'alertsDesc': 'تنبيهات أمنية من قاعدة البيانات',
    'critical': 'حرج', 'warning': 'تحذير', 'all': 'الكل',
    'noAlerts': 'لا توجد تنبيهات', 'noAlertsDesc': 'لم يتم اكتشاف أي فدية في فحوصاتك',
    'clearAllAlerts': 'مسح كل التنبيهات', 'clearAllAlertsDesc': 'حذف جميع تنبيهات الفدية من قاعدة البيانات',
    'clearAllAlertsConfirm': 'حذف جميع التنبيهات؟ لا يمكن التراجع.',
    'clearingAlerts': 'جاري المسح...',
    'settingsTitle': 'الإعدادات', 'settingsDesc': 'تخصيص إعدادات الحماية والأمان',
    'language': 'اللغة', 'interfaceLang': 'لغة الواجهة', 'chooseLang': 'اختر لغتك المفضلة',
    'protectionSettings': 'إعدادات الحماية', 'realtimeProtection': 'الحماية الفورية',
    'realtimeDesc': 'فحص الملفات تلقائياً عند الوصول إليها', 'autoQuarantine': 'الحجر التلقائي',
    'autoQuarantineDesc': 'نقل الملفات المشبوهة إلى الحجر', 'scanOnStartup': 'الفحص عند التشغيل',
    'scanOnStartupDesc': 'تشغيل فحص سريع عند بدء النظام', 'notifications': 'الإشعارات',
    'notificationsDesc': 'عرض التنبيهات عند اكتشاف تهديدات', 'updateBackup': 'التحديث والنسخ الاحتياطي',
    'autoUpdate': 'التحديث التلقائي', 'autoUpdateDesc': 'تحديث قاعدة بيانات التهديدات تلقائياً',
    'scheduledScan': 'الفحص المجدول', 'scheduledScanDesc': 'تشغيل فحص كامل يومياً الساعة 2:00 صباحاً',
    'cloudBackup': 'النسخ السحابي', 'cloudBackupDesc': 'نسخ احتياطي للملفات المهمة على السحابة',
    'sensitivity': 'مستوى الحساسية', 'sensitivityDesc': 'أعلى = تنبيهات أكثر، أقل = إيجابيات كاذبة أقل',
    'low': 'منخفض', 'medium': 'متوسط', 'high': 'عالي', 'dangerZone': 'منطقة الخطر',
    'clearAll': 'مسح جميع بيانات الفحص', 'clearDesc': 'حذف جميع السجلات من قاعدة البيانات نهائياً',
    'clearDB': 'مسح DB', 'save': 'حفظ', 'saved': 'تم الحفظ!', 'reset': 'إعادة تعيين',
    'login': 'تسجيل الدخول', 'register': 'إنشاء حساب', 'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور', 'confirmPassword': 'تأكيد كلمة المرور', 'username': 'اسم المستخدم',
    'loginBtn': 'تسجيل الدخول', 'registerBtn': 'إنشاء الحساب',
    'noAccount': 'ليس لديك حساب؟', 'hasAccount': 'لديك حساب بالفعل؟',
    'signUpLink': 'سجل الآن', 'signInLink': 'سجل دخولك',
    'emailPlaceholder': 'أدخل بريدك الإلكتروني', 'passwordPlaceholder': 'أدخل كلمة المرور',
    'Forgot Password': 'نسيت كلمة المرور',
    'forgotPassword': 'نسيت كلمة المرور',
    'Send Code': 'إرسال الرمز',
    'Reset Code': 'إعادة تعيين الرمز',
    'New Password': 'كلمة مرور جديدة',
    'Reset Password': 'إعادة تعيين كلمة المرور',
    'confirmPasswordPlaceholder': 'أعد إدخال كلمة المرور', 'usernamePlaceholder': 'اختر اسم مستخدم',
    'verifyEmail': 'تحقق من بريدك الإلكتروني', 'verifyDesc': 'أرسلنا رمزاً مكوناً من 6 أرقام إلى',
    'verifyCode': 'رمز التحقق', 'verifyBtn': 'تحقق من البريد',
    'resendCode': 'إعادة الإرسال', 'resendIn': 'إعادة الإرسال خلال', 'seconds': 'ث',
    'verifyPlaceholder': 'أدخل الرمز المكون من 6 أرقام', 'loginSuccess': 'مرحباً بعودتك!',
    'logoutBtn': 'تسجيل الخروج', 'loggedInAs': 'مسجل دخول كـ',
    'passwordMismatch': 'كلمتا المرور غير متطابقتين', 'emailInvalid': 'يرجى إدخال بريد إلكتروني صالح',
    'usernameTooShort': 'اسم المستخدم يجب أن يكون 3 أحرف على الأقل',
    'passwordTooShort': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    'accountCreated': 'تم إنشاء الحساب! يرجى التحقق من بريدك.',
    'invalidCode': 'رمز التحقق غير صحيح', 'codeExpired': 'انتهت صلاحية الرمز، يرجى إعادة الإرسال',
    'loginError': 'البريد الإلكتروني أو كلمة المرور غير صحيحة', 'protectedBy': 'محمي بواسطة SARMZ RansomGuard',
    'downloadReport': 'تنزيل تقرير PDF', 'generatingReport': 'جاري إنشاء التقرير...',
    'reportTitle': 'تقرير تحليل الأمان', 'reportGenerated': 'تم إنشاء التقرير',
    'reportSubtitle': 'SARMZ RansomGuard - تحليل شامل',
    'reportSummary': 'الملخص التنفيذي', 'reportScans': 'سجل الفحوصات',
    'reportMetrics': 'مقاييس أداء النموذج', 'reportProtection': 'حالة الحماية',
    'reportFooter': 'تم الإنشاء بواسطة SARMZ RansomGuard - نظام كشف برامج الفدية',
    'totalFiles': 'إجمالي الملفات المفحوصة', 'threatsBlocked': 'التهديدات المحظورة',
    'safeFilesCount': 'الملفات الآمنة', 'avgConfidenceScore': 'متوسط درجة الثقة',
    'trainingTitle': 'تدريب النموذج',
    'profileSettings': 'إعدادات الملف الشخصي',
    'changeUsername': 'تغيير اسم المستخدم',
    'newUsername': 'اسم المستخدم الجديد',
    'changePassword': 'تغيير كلمة المرور',
    'newPassword': 'كلمة المرور الجديدة',
    'updateProfileBtn': 'تحديث الملف الشخصي',
    'profileUpdated': 'تم تحديث الملف الشخصي بنجاح!',
    'aboutTitle': 'حول النظام', 'aboutDesc': 'تعرف أكثر على SARMZ RansomGuard',
    'aboutWelcome': 'عن SARMZ RansomGuard',
    'aboutWelcomeDesc': 'مرحباً بكم في SARMZ RansomGuard، منصة ذكية ومتقدمة مخصصة للأمن السيبراني الاستباقي. مهمتنا هي حماية بيئتك الرقمية من خلال اكتشاف تهديدات برامج الفدية (Ransomware) وتحييدها قبل أن تتسبب في أي ضرر أو تشفير لبياناتك الثمينة.',
    'aboutApproach': 'كيف نعمل؟',
    'aboutApproachDesc': 'بالاعتماد على أحدث تقنيات الذكاء الاصطناعي وخوارزميات تعلم الآلة (Machine Learning)، يقوم SARMZ RansomGuard بتحليل دقيق لملفات الويندوز التنفيذية (.exe). من خلال فحص الأنماط المعقدة مثل بنية الملف (PE Structure)، والإنتروبيا (Entropy)، والقواعد الأمنية (YARA Rules)، يستطيع نظامنا التمييز بين البرمجيات الآمنة والخبيثة بدقة وموثوقية عالية.',
    'aboutWhy': 'لماذا SARMZ RansomGuard؟',
    'aboutWhyDesc': 'مع تزايد تعقيد هجمات برامج الفدية، لم تعد طرق الحماية التقليدية كافية. يأتي SARMZ RansomGuard ليسد هذه الفجوة من خلال توفير آلية دفاع ذكية تتنبأ بالخطر قبل وقوعه. توفر واجهتنا التفاعلية تحليلات في الوقت الفعلي، سجلات فحص شاملة، وتقارير أمنية مفصلة، مما يمنح المستخدمين سيطرة كاملة على أمن أجهزتهم.',
    'aboutVision': 'رؤيتنا',
    'aboutVisionDesc': 'تم تطوير هذا النظام ليعكس التزامنا بابتكار حلول تقنية حديثة وفعالة. نحن نؤمن بأن الأمان الرقمي حق للجميع، ونسعى لتقديم أداة تجمع بين قوة الذكاء الاصطناعي وسهولة الاستخدام لمواجهة أشرس التهديدات الرقمية اليوم.',
    'lastAction': 'آخر إجراء', 'realtimeShield': 'درع الحماية الحقيقي',
    'topRecentThreats': 'التهديدات الحرجة', 'nextScheduledScan': 'التدقيق القادم',
    'activeStatus': 'نشط', 'total': 'الإجمالي',
    'noRecentThreats': 'لا توجد تهديدات', 'justNow': 'الآن',



  }
}

export function getLang(): Lang {
  try {
    const s = localStorage.getItem('ransomguard_settings')
    if (s) return JSON.parse(s).lang || 'en'
  } catch { }
  return 'en'
}
